package indexingTopology.compression.DataCompression;

/**
 * Create by zelin on 17-9-6
 **/
public class ColumnDataType {
    public static String[] types = {
            "class java.lang.Long",
            "class java.lang.Float",
            "class java.lang.Float",
            "class java.lang.Float",
            "class java.lang.Float",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Short",
            "class java.lang.Short",
            "class java.lang.Byte",
            "class java.lang.Byte",
            "class java.lang.Float",
            "class java.lang.Float",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
            "class java.lang.Double",
    };



}
